[build]
  command = "next build"
  publish = ".next"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
